apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "jrebterraformacr.azurecr.io": {
          "username": "{{ .Values.acr.username }}",
          "password": "{{ .Values.acr.password }}",
          "email": "you@example.com"
        }
      }
    }
